apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: automationrun1
  description: QA details
  annotations:
    harness.io/cicd-accountIdentifier: vpCkHKsDSxK9_KYfjCTMKA
    harness.io/cicd-orgIdentifier: QE_Team
    harness.io/cicd-projectIdentifier: Quality_Assurence
    harness.io/ci-pipelineIdentifier: p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12
    harness.io/cd-serviceId: automationrun
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
